services:
  - type: web
    name: smart-bookmark-manager-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python migrate_db.py
      python create_initial_data.py
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql://smart_bookmark_db_user:ZKhFRlrOd3vA5yDVsUdupKPQ9iRHlRUn@dpg-d4m420ogjchc73b1hlg0-a.oregon-postgres.render.com/smart_bookmark_db
      - key: ENVIRONMENT
        value: production